<?php
/**
 * Generate generated/constants.ts from the plugin's PHP constants so the web
 * layer shares one source of truth. Reads the constants declared in the main
 * bootstrap and any Core class constants, emits an `as const` object + a union.
 *
 * @package X06CacheActions
 */

declare(strict_types=1);

$root      = dirname( __DIR__ );
$bootstrap = $root . '/x06-cache-actions.php';
$out_dir   = $root . '/generated';

$constants = array();

// Top-level `const NAME = 'value';` and `define( 'NAME', 'value' )` declarations.
if ( is_file( $bootstrap ) ) {
	$src = (string) file_get_contents( $bootstrap );
	if ( preg_match_all( "/const\\s+(X06_CACHE_ACTIONS_[A-Z0-9_]+)\\s*=\\s*'([^']*)'/", $src, $m, PREG_SET_ORDER ) ) {
		foreach ( $m as $match ) {
			$constants[ $match[1] ] = $match[2];
		}
	}

	// The other spelling. A bootstrap-only main file commonly declares plugin
	// constants with `define( 'NAME', 'value' )` rather than the `const`
	// keyword above, and the two are not interchangeable to a regex. Matching
	// only `const` meant such a plugin extracted NOTHING, and the drift gate
	// then compared an empty file to an empty file and reported green -- for
	// the whole life of the contract. Only string literals are taken, so
	// `define( '..._FILE', __FILE__ )` is correctly skipped.
	if ( preg_match_all( "/define\\(\\s*'(X06_CACHE_ACTIONS_[A-Z0-9_]+)'\\s*,\\s*'([^']*)'\\s*\\)/", $src, $m, PREG_SET_ORDER ) ) {
		foreach ( $m as $match ) {
			$constants[ $match[1] ] = $match[2];
		}
	}

	// A bootstrap that exists but yields nothing means its declarations are in
	// a form neither pattern above recognises -- not that the plugin genuinely
	// has no constants, since the scaffold always ships X06_CACHE_ACTIONS_VERSION.
	// Failing loudly is the difference between a gate that cannot pass and one
	// that cannot fail. The second is worse: it gets counted as coverage.
	if ( array() === $constants ) {
		fwrite( STDERR, "gen-constants: {$bootstrap} declares no X06_CACHE_ACTIONS_* string constants this script can read.\n" );
		fwrite( STDERR, "Recognised forms: const NAME = 'value';  and  define( 'NAME', 'value' );\n" );
		exit( 1 );
	}
}

if ( ! is_dir( $out_dir ) ) {
	mkdir( $out_dir, 0775, true );
}

$entries = array();
foreach ( $constants as $name => $value ) {
	$entries[] = sprintf( "  %s: %s,", $name, json_encode( $value ) );
}

$keys  = array_map( static fn ( $k ) => json_encode( $k ), array_keys( $constants ) );
$union = empty( $keys ) ? 'never' : implode( ' | ', $keys );

$ts  = "// AUTO-GENERATED by scripts/gen-constants.php. Do not edit.\n";
$ts .= "export const CONSTANTS = {\n" . implode( "\n", $entries ) . "\n} as const;\n\n";
$ts .= "export type ConstantName = $union;\n";

file_put_contents( $out_dir . '/constants.ts', $ts );

if ( empty( $constants ) ) {
	echo "[gen:const] no X06_CACHE_ACTIONS_* constants found in {$bootstrap} — wrote empty generated/constants.ts.\n";
} else {
	echo 'Wrote generated/constants.ts (' . count( $constants ) . " constant(s)).\n";
}
